# -*- coding: utf-8 -*-
"""01_eda.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pGuyjRxgJuQmLYvuGP-6ZBMgV5fRSsu8
"""

# Commented out IPython magic to ensure Python compatibility.
"""
B2B Revenue Intelligence — EDA Script
Optimized for Google Colab

HOW TO USE:
    1. Open Google Colab (colab.research.google.com)
    2. Create a new notebook
    3. In the first cell, run:
            !git clone https://github.com/thaispaulino/b2b-revenue-intelligence.git
#             %cd b2b-revenue-intelligence
            !python src/generate_dataset.py
    4. In the second cell, run:
            exec(open('notebooks/01_eda.py').read())

    OR simply paste this entire script into a Colab cell and run it.
"""

import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.ticker as mticker
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

NAVY   = '#1E2761'
TEAL   = '#028090'
MINT   = '#02C39A'
ACCENT = '#00B4D8'
GRAY   = '#64748B'
PALETTE = [NAVY, TEAL, MINT, ACCENT, '#F4A261', '#E76F51']
NBA_COLORS = {'Upsell': MINT, 'Expand': TEAL, 'Nurture': ACCENT, 'Retain': '#E76F51'}

plt.rcParams.update({
    'figure.facecolor': 'white',
    'axes.facecolor':   'white',
    'axes.spines.top':  False,
    'axes.spines.right':False,
    'axes.labelcolor':  NAVY,
    'axes.titlecolor':  NAVY,
    'axes.titlesize':   13,
    'axes.titleweight': 'bold',
    'font.family':      'sans-serif',
    'xtick.color':      GRAY,
    'ytick.color':      GRAY,
})
sns.set_palette(PALETTE)

DATA_PATH = '/content/'

print("Loading data...")
acc     = pd.read_csv(f'{DATA_PATH}/accounts.csv')
subs    = pd.read_csv(f'{DATA_PATH}/product_subscriptions.csv')
metrics = pd.read_csv(f'{DATA_PATH}/monthly_metrics.csv')
health  = pd.read_csv(f'{DATA_PATH}/account_health.csv')
am      = pd.read_csv(f'{DATA_PATH}/am.csv')

latest_month  = health['month'].max()
health_latest = health[health['month'] == latest_month].copy()

print(f"  Accounts:      {len(acc):,}")
print(f"  Subscriptions: {len(subs):,}")
print(f"  Monthly rows:  {len(metrics):,}")
print(f"  Health rows:   {len(health):,}")
print(f"  Latest month:  {latest_month}")
print()

# 1. PORTFOLIO OVERVIEW

OUT_PATH = '/content/'
print("=" * 60)
print("  1. PORTFOLIO OVERVIEW")
print("=" * 60)

fig, axes = plt.subplots(1, 3, figsize=(16, 5))
fig.suptitle('Portfolio Composition — 500 Enterprise Accounts',
             fontsize=15, fontweight='bold', color=NAVY, y=1.02)

# Segment pie
seg_counts = acc['client_segment'].value_counts()
axes[0].pie(seg_counts, labels=seg_counts.index, autopct='%1.0f%%',
            colors=PALETTE[:3], startangle=90,
            wedgeprops={'edgecolor': 'white', 'linewidth': 2})
axes[0].set_title('By Client Segment')

# Industry bar
ind_counts = acc['industry_vertical'].value_counts()
bars = axes[1].barh(ind_counts.index[::-1], ind_counts.values[::-1], color=PALETTE)
axes[1].set_title('By Industry Vertical')
axes[1].set_xlabel('Number of accounts')
for bar, val in zip(bars, ind_counts.values[::-1]):
    axes[1].text(val + 1, bar.get_y() + bar.get_height()/2,
                 str(val), va='center', color=GRAY, fontsize=10)

# Region bar
reg_counts = acc['client_region'].value_counts()
axes[2].bar(reg_counts.index, reg_counts.values, color=TEAL, alpha=0.85)
axes[2].set_title('By Client Region')
axes[2].tick_params(axis='x', rotation=35)

plt.tight_layout()
plt.savefig(f'{OUT_PATH}/01_portfolio_composition.png', dpi=150, bbox_inches='tight')
plt.show()

total_arr  = acc['arr_sek'].sum()
avg_arr    = acc['arr_sek'].mean()
avg_tenure = acc['tenure_months'].mean()
print(f"  Total ARR:          SEK {total_arr:,.0f}")
print(f"  Avg ARR:            SEK {avg_arr:,.0f}")
print(f"  Avg tenure:         {avg_tenure:.1f} months ({avg_tenure/12:.1f} years)")
print(f"  Overall churn rate: {acc['churned'].mean():.1%}")
print()
print("  ARR by Segment:")
print(acc.groupby('client_segment')['arr_sek']
        .agg(['count','mean','sum'])
        .rename(columns={'count':'Accounts','mean':'Avg ARR','sum':'Total ARR'})
        .to_string())
print()
print("  💡 Enterprise (26% of accounts) drives disproportionate ARR.")
print("     A single Enterprise churn = ~50 SMB churns in revenue impact.")
print()

print("=" * 60)
print("  2. CHURN ANALYSIS")
print("=" * 60)

fig, axes = plt.subplots(1, 3, figsize=(16, 5))
fig.suptitle('Churn Rate Analysis', fontsize=15, fontweight='bold', color=NAVY, y=1.02)

# By segment
churn_seg = acc.groupby('client_segment')['churned'].mean().sort_values(ascending=False)
bars = axes[0].bar(churn_seg.index, churn_seg.values * 100,
                   color=[TEAL if v < 0.15 else '#E76F51' for v in churn_seg.values])
axes[0].set_title('Churn Rate by Segment')
axes[0].set_ylabel('Churn Rate (%)')
axes[0].axhline(acc['churned'].mean() * 100, color=GRAY, linestyle='--',
                linewidth=1, label='Portfolio avg')
axes[0].legend(fontsize=9)
for bar, val in zip(bars, churn_seg.values):
    axes[0].text(bar.get_x() + bar.get_width()/2, bar.get_height() + 0.3,
                 f'{val:.1%}', ha='center', fontsize=11, fontweight='bold', color=NAVY)

# By industry
churn_ind = acc.groupby('industry_vertical')['churned'].mean().sort_values(ascending=True)
axes[1].barh(churn_ind.index,
             churn_ind.values * 100,
             color=['#E76F51' if v > 0.15 else TEAL for v in churn_ind.values])
axes[1].set_title('Churn Rate by Industry')
axes[1].set_xlabel('Churn Rate (%)')
axes[1].axvline(acc['churned'].mean() * 100, color=GRAY, linestyle='--', linewidth=1)

# By tenure bucket
acc['tenure_bucket'] = pd.cut(acc['tenure_months'],
                               bins=[0, 6, 12, 24, 60],
                               labels=['0-6m', '6-12m', '12-24m', '24m+'])
churn_tenure = acc.groupby('tenure_bucket', observed=True)['churned'].mean()
axes[2].bar(churn_tenure.index.astype(str), churn_tenure.values * 100,
            color=[PALETTE[i] for i in range(len(churn_tenure))])
axes[2].set_title('Churn Rate by Tenure')
axes[2].set_ylabel('Churn Rate (%)')
axes[2].set_xlabel('Tenure bucket')

plt.tight_layout()
plt.savefig(f'{OUT_PATH}/02_churn_analysis.png', dpi=150, bbox_inches='tight')
plt.show()

print(f"  SMB churn ({churn_seg['SMB']:.1%}) is {churn_seg['SMB']/churn_seg['Enterprise']:.0f}x higher than Enterprise ({churn_seg['Enterprise']:.1%})")
print(f"  Highest risk industry: {churn_ind.index[-1]} ({churn_ind.values[-1]:.1%})")
print("  💡 First 6 months = critical onboarding window (highest churn risk)")
print()

# ─────────────────────────────────────────────────────────────────────────────
# 3. PRODUCT ADOPTION — WHITE SPACE FOUNDATION
# ─────────────────────────────────────────────────────────────────────────────
print("=" * 60)
print("  3. PRODUCT ADOPTION — WHITE SPACE FOUNDATION")
print("=" * 60)

fig, axes = plt.subplots(1, 2, figsize=(16, 5))
fig.suptitle('Product Adoption Patterns', fontsize=15, fontweight='bold', color=NAVY, y=1.02)

# Overall adoption rate
prod_counts  = subs['product_line'].value_counts()
adoption_pct = (prod_counts / len(acc) * 100).round(1)
bars = axes[0].barh(prod_counts.index[::-1], adoption_pct.values[::-1],
                    color=PALETTE[:len(prod_counts)])
axes[0].set_title('Product Adoption Rate (% of accounts)')
axes[0].set_xlabel('% of accounts using product')
for bar, val in zip(bars, adoption_pct.values[::-1]):
    axes[0].text(val + 0.5, bar.get_y() + bar.get_height()/2,
                 f'{val}%', va='center', fontsize=11, fontweight='bold', color=NAVY)

# Heatmap by industry
subs_with_ind = subs.merge(acc[['client_id', 'industry_vertical']], on='client_id')
heatmap_data  = pd.crosstab(subs_with_ind['industry_vertical'],
                              subs_with_ind['product_line'])
ind_totals    = acc['industry_vertical'].value_counts()
heatmap_norm  = heatmap_data.div(ind_totals, axis=0).round(2) * 100

sns.heatmap(heatmap_norm, annot=True, fmt='.0f', cmap='YlOrRd',
            linewidths=0.5, ax=axes[1],
            cbar_kws={'label': '% of accounts in industry'},
            annot_kws={'size': 11})
axes[1].set_title('Product Adoption by Industry (%)')
axes[1].set_xlabel('Product Line')
axes[1].set_ylabel('')
axes[1].tick_params(axis='x', rotation=20)

plt.tight_layout()
plt.savefig(f'{OUT_PATH}/03_product_adoption.png', dpi=150, bbox_inches='tight')
plt.show()

# White space gaps
print("  WHITE SPACE MATRIX (0 = no accounts in industry using this product):")
print()
print(heatmap_data.to_string())
print()
print("  KEY WHITE SPACE OPPORTUNITIES:")
for industry in heatmap_data.index:
    gaps = heatmap_data.loc[industry][heatmap_data.loc[industry] == 0].index.tolist()
    if gaps:
        n_accounts = ind_totals[industry]
        print(f"    {industry:30s} → Missing: {gaps} ({n_accounts} accounts)")
print()

# ─────────────────────────────────────────────────────────────────────────────
# 4. REVENUE & GROSS PROFIT
# ─────────────────────────────────────────────────────────────────────────────
print("=" * 60)
print("  4. REVENUE & GROSS PROFIT")
print("=" * 60)

monthly_total = metrics.groupby('month').agg(
    revenue=('revenue_sek', 'sum'),
    gp=('gross_profit_sek', 'sum')
).reset_index()
monthly_total['gp_margin'] = monthly_total['gp'] / monthly_total['revenue']

fig, axes = plt.subplots(1, 2, figsize=(16, 5))
fig.suptitle('Revenue & Gross Profit Trends', fontsize=15, fontweight='bold', color=NAVY, y=1.02)

# Revenue + GP over time
x = range(len(monthly_total))
axes[0].fill_between(x, monthly_total['revenue']/1e6, alpha=0.3, color=TEAL)
axes[0].plot(x, monthly_total['revenue']/1e6, color=TEAL, linewidth=2.5, label='Revenue')
axes[0].fill_between(x, monthly_total['gp']/1e6, alpha=0.3, color=NAVY)
axes[0].plot(x, monthly_total['gp']/1e6, color=NAVY, linewidth=2.5, label='Gross Profit')
axes[0].set_xticks(x)
axes[0].set_xticklabels(monthly_total['month'], rotation=35, fontsize=8)
axes[0].set_ylabel('SEK (millions)')
axes[0].set_title('Portfolio Revenue vs Gross Profit (Monthly)')
axes[0].legend()
axes[0].yaxis.set_major_formatter(mticker.FuncFormatter(lambda v, _: f'{v:.1f}M'))

# Revenue by product line
rev_by_product = metrics.groupby('product_line')['revenue_sek'].sum().sort_values(ascending=True)
bars = axes[1].barh(rev_by_product.index, rev_by_product.values/1e6,
                    color=PALETTE[:len(rev_by_product)])
axes[1].set_title('Total Revenue by Product Line')
axes[1].set_xlabel('Total Revenue (SEK millions)')
for bar, val in zip(bars, rev_by_product.values/1e6):
    axes[1].text(val + 0.1, bar.get_y() + bar.get_height()/2,
                 f'{val:.1f}M', va='center', fontsize=10, color=NAVY)

plt.tight_layout()
plt.savefig(f'{OUT_PATH}/05_revenue_analysis.png', dpi=150, bbox_inches='tight')
plt.show()

print(f"  Avg GP Margin: {monthly_total['gp_margin'].mean():.1%}")
print()

# ─────────────────────────────────────────────────────────────────────────────
# 5. NEXT BEST ACTION (NBA) ANALYSIS
# ─────────────────────────────────────────────────────────────────────────────
print("=" * 60)
print("  5. NEXT BEST ACTION ANALYSIS")
print("=" * 60)

fig, axes = plt.subplots(1, 3, figsize=(16, 5))
fig.suptitle('Next Best Action — Label Analysis (Latest Month)',
             fontsize=15, fontweight='bold', color=NAVY, y=1.02)

# Distribution
nba_dist = health_latest['nba_label'].value_counts()
axes[0].bar(nba_dist.index, nba_dist.values,
            color=[NBA_COLORS[l] for l in nba_dist.index])
axes[0].set_title('NBA Label Distribution')
axes[0].set_ylabel('Number of accounts')
for i, (label, val) in enumerate(zip(nba_dist.index, nba_dist.values)):
    axes[0].text(i, val + 2, str(val), ha='center', fontweight='bold', color=NAVY)

# MoM growth by NBA
nba_growth = health_latest.groupby('nba_label')['mom_revenue_growth'].mean().sort_values(ascending=False)
bars = axes[1].bar(nba_growth.index, nba_growth.values * 100,
                   color=[NBA_COLORS[l] for l in nba_growth.index])
axes[1].axhline(0, color=GRAY, linewidth=1)
axes[1].set_title('Avg MoM Revenue Growth by NBA Label')
axes[1].set_ylabel('MoM Growth (%)')
for bar, val in zip(bars, nba_growth.values):
    axes[1].text(bar.get_x() + bar.get_width()/2,
                 bar.get_height() + (0.05 if val >= 0 else -0.15),
                 f'{val:.2%}', ha='center', fontsize=10, fontweight='bold', color=NAVY)

# NPS by NBA
nba_nps = health_latest.groupby('nba_label')['nps_score_proxy'].mean().sort_values(ascending=False)
axes[2].bar(nba_nps.index, nba_nps.values,
            color=[NBA_COLORS[l] for l in nba_nps.index])
axes[2].set_title('Avg NPS Score by NBA Label')
axes[2].set_ylabel('Avg NPS (1-10)')
axes[2].set_ylim(0, 10)
for i, (label, val) in enumerate(zip(nba_nps.index, nba_nps.values)):
    axes[2].text(i, val + 0.1, f'{val:.1f}', ha='center', fontweight='bold', color=NAVY)

plt.tight_layout()
plt.savefig(f'{OUT_PATH}/06_nba_analysis.png', dpi=150, bbox_inches='tight')
plt.show()

print("  NBA Label Summary:")
print(health_latest.groupby('nba_label').agg(
    accounts=('client_id', 'count'),
    avg_revenue_sek=('total_revenue_sek', 'mean'),
    avg_mom_growth=('mom_revenue_growth', 'mean'),
    avg_nps=('nps_score_proxy', 'mean'),
    avg_ltv_sek=('ltv_12m_estimate_sek', 'mean')
).round(2).to_string())
print()
print("  💡 Labels are well-separated — Upsell (+5.3% MoM) vs Retain (-1.4% MoM)")
print("     Model should distinguish these patterns cleanly.")
print()

# ─────────────────────────────────────────────────────────────────────────────
# 6. LTV DISTRIBUTION
# ─────────────────────────────────────────────────────────────────────────────
print("=" * 60)
print("  6. LTV DISTRIBUTION")
print("=" * 60)

fig, axes = plt.subplots(1, 2, figsize=(16, 5))
fig.suptitle('LTV (12-Month Estimate) Analysis', fontsize=15, fontweight='bold', color=NAVY, y=1.02)

for seg, color in zip(['Enterprise', 'Mid-Market', 'SMB'], [NAVY, TEAL, MINT]):
    subset = health_latest[health_latest['client_segment'] == seg]['ltv_12m_estimate_sek'] / 1e6
    axes[0].hist(subset, bins=20, alpha=0.6, label=seg, color=color)
axes[0].set_title('LTV Distribution by Segment')
axes[0].set_xlabel('LTV 12m (SEK millions)')
axes[0].set_ylabel('Number of accounts')
axes[0].legend()

colors_map = {'Enterprise': NAVY, 'Mid-Market': TEAL, 'SMB': MINT}
for seg in ['Enterprise', 'Mid-Market', 'SMB']:
    subset = health_latest[health_latest['client_segment'] == seg]
    axes[1].scatter(subset['tenure_months'], subset['ltv_12m_estimate_sek']/1e6,
                    alpha=0.5, color=colors_map[seg], label=seg, s=25)
axes[1].set_title('LTV vs Account Tenure')
axes[1].set_xlabel('Tenure (months)')
axes[1].set_ylabel('LTV 12m (SEK millions)')
axes[1].legend()

plt.tight_layout()
plt.savefig(f'{OUT_PATH}/07_ltv_analysis.png', dpi=150, bbox_inches='tight')
plt.show()
print()

# ─────────────────────────────────────────────────────────────────────────────
# 7. FEATURE CORRELATIONS
# ─────────────────────────────────────────────────────────────────────────────
print("=" * 60)
print("  7. FEATURE CORRELATIONS")
print("=" * 60)

corr_df = health_latest[[
    'tenure_months', 'active_products_count', 'total_revenue_sek',
    'mom_revenue_growth', 'nps_score_proxy', 'support_tickets_30d',
    'days_since_last_contact', 'months_to_renewal', 'gp_margin',
    'ltv_12m_estimate_sek', 'churned'
]].copy()

fig, axes = plt.subplots(1, 2, figsize=(16, 6))
fig.suptitle('Feature Correlations', fontsize=15, fontweight='bold', color=NAVY, y=1.02)

corr_matrix = corr_df.corr()
mask = np.triu(np.ones_like(corr_matrix, dtype=bool))
sns.heatmap(corr_matrix, mask=mask, annot=True, fmt='.2f',
            cmap='RdBu_r', center=0, linewidths=0.5, ax=axes[0],
            annot_kws={'size': 8}, vmin=-1, vmax=1)
axes[0].set_title('Feature Correlation Matrix')
axes[0].tick_params(axis='x', rotation=45)

churn_corr = corr_df.corr()['churned'].drop('churned').sort_values()
axes[1].barh(churn_corr.index, churn_corr.values,
             color=['#E76F51' if v > 0 else TEAL for v in churn_corr.values])
axes[1].axvline(0, color=GRAY, linewidth=1)
axes[1].set_title('Feature Correlation with Churn')
axes[1].set_xlabel('Correlation coefficient')

plt.tight_layout()
plt.savefig(f'{OUT_PATH}/08_correlations.png', dpi=150, bbox_inches='tight')
plt.show()
print()

# ─────────────────────────────────────────────────────────────────────────────
# 8. EXECUTIVE SUMMARY
# ─────────────────────────────────────────────────────────────────────────────
upsell_accounts  = (health_latest['nba_label'] == 'Upsell').sum()
retain_accounts  = (health_latest['nba_label'] == 'Retain').sum()
upsell_ltv_total = health_latest[health_latest['nba_label'] == 'Upsell']['ltv_12m_estimate_sek'].sum()

print()
print("=" * 60)
print("  B2B REVENUE INTELLIGENCE — EDA SUMMARY")
print("=" * 60)
print(f"""
📊 PORTFOLIO
   500 enterprise accounts | SEK {acc['arr_sek'].sum()/1e6:.0f}M total ARR
   Avg tenure: {acc['tenure_months'].mean():.0f} months | Churn rate: {acc['churned'].mean():.1%}

🚨 CHURN RISK
   SMB churn (25.8%) is 8x higher than Enterprise (3.1%)
   Gaming & Entertainment = highest-risk industry (24.1%)
   First 6 months = critical onboarding window

🗺️  WHITE SPACE OPPORTUNITIES
   Fintech      → 0 Email adoption        (90 accounts missing)
   Retail       → 0 Verification adoption (123 accounts missing)
   Logistics    → 0 Email adoption        (82 accounts missing)

🎯 NEXT BEST ACTION (latest month)
   Upsell:  {upsell_accounts} accounts (+5.3% MoM) → SEK {upsell_ltv_total/1e6:.0f}M LTV pool
   Retain:  {retain_accounts} accounts (-1.4% MoM) → intervention needed
   Nurture: 233 accounts → maintain engagement
   Expand:   59 accounts → deepen Enterprise relationships

💰 REVENUE
   SMS drives highest total revenue
   WhatsApp Business has highest revenue per message
   Enterprise avg monthly revenue: SEK 474K vs SMB SEK 42K
""")
print("=" * 60)
print("  EDA Complete ✅ — Ready for modeling")
print("  Next: 02_white_space_model.py")
print("=" * 60)